# Generated by Django 4.2.23 on 2025-09-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly salary in rupees', max_digits=10),
        ),
    ]
