# Generated by Django 4.2.23 on 2025-09-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Springfield High School', max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('google_upi_id', models.CharField(blank=True, help_text='Google UPI ID for fee payments', max_length=100, null=True)),
                ('razorpay_id', models.CharField(blank=True, help_text='Razorpay merchant ID', max_length=100, null=True)),
                ('academic_year', models.CharField(default='2024-2025', max_length=20)),
                ('school_timings', models.CharField(default='8:00 AM - 3:00 PM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
