# Generated by Django 4.2.23 on 2025-09-18 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key for the setting', max_length=100)),
                ('label', models.CharField(help_text='Display label for the setting', max_length=200)),
                ('value', models.TextField(blank=True, help_text='The setting value')),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('url', 'URL'), ('textarea', 'Textarea'), ('file', 'File')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False, help_text='Whether this setting is required')),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('file_data', models.BinaryField(blank=True, help_text='Binary data for file uploads', null=True)),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('file_mime_type', models.CharField(blank=True, help_text='File MIME type', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.school')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('school', 'key')},
            },
        ),
    ]
