# Generated by Django 4.2.23 on 2025-09-19 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_paymentgateway_fee_overdue_date_fee_waived_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
