# Generated by Django 4.2.23 on 2025-09-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_fee_options_fee_notes_fee_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherReimbursementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requested', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_approval', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_stats', to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherGradeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_grades', models.PositiveIntegerField(default=0)),
                ('graded_today', models.PositiveIntegerField(default=0)),
                ('average_grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('late_submissions', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_stats', to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('present_today', models.PositiveIntegerField(default=0)),
                ('late_today', models.PositiveIntegerField(default=0)),
                ('absent_today', models.PositiveIntegerField(default=0)),
                ('overall_attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssignmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('pending_submissions', models.PositiveIntegerField(default=0)),
                ('graded_assignments', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_stats', to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('total_students', models.PositiveIntegerField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_rank', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_borrowed', models.PositiveIntegerField(default=0)),
                ('books_due_soon', models.PositiveIntegerField(default=0)),
                ('books_overdue', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_stats', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('period_number', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_timetable', to='api.schoolclass')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_schedule', to='api.teacher')),
            ],
            options={
                'ordering': ['day_of_week', 'period_number'],
                'unique_together': {('school_class', 'day_of_week', 'period_number')},
            },
        ),
    ]
